"""SEC-S5: Ensemble retest — 15m R4 (TOP-4 trend-cont) + MR pool (PASS strategies).

Compares 4 scenarios:
  A. Baseline R4 (TOP-4 trend-cont only) - reference
  B. R4 + bollinger_fade_mr
  C. R4 + range_bo_failure_mr
  D. R4 + all PASS MR strategies (TOP-N)

For each scenario:
  - Walk-forward 34 windows (2y train + 3mo OOS + 1mo step, sec31 pattern)
  - Per-month breakdown (61 months)
  - Critical metrics: zero months, neg months, CV, mean, annual

Compares to user mandate:
  - Sıfır ay 20 -> <=8
  - Negatif ay 9 -> <=6
  - CV 223% -> <=100%
  - Mean +17.33% -> >=20% (preserve)
  - Annual +735% -> >=400% (acceptable decline)

Inputs:
  data/sec31_15m_pool.pkl  (TOP-4 trend-cont trades)
  data/sec_s5_mr_pool.pkl  (MR strategy trades, generated by sec_s5_mr_pool_standalone.py)

Output:
  reports/researcher/2026-05-17_sec_s5_mr_ensemble_retest.md
"""
from __future__ import annotations
import io, os, pickle, sys
from dataclasses import replace
from datetime import datetime, timezone
from pathlib import Path
from statistics import mean as stat_mean, stdev

if __name__ == "__main__":
    try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    except Exception: pass

os.environ["PA_LOG_QUIET"] = "1"
import warnings; warnings.filterwarnings("ignore")
import logging; logging.getLogger("price_action").setLevel(logging.ERROR)

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT)); sys.path.insert(0, str(ROOT / "src"))

import pandas as pd
from price_action.backtest.lab import ProductionConfig, production_replay

POOL_R4 = ROOT / "data" / "sec31_15m_pool.pkl"
POOL_MR = ROOT / "data" / "sec_s5_mr_pool.pkl"
YAML_R3 = ROOT / "configs" / "risk_phoenix_scalp_15m_pyramid_r3.yaml"
REPORT_OUT = ROOT / "reports" / "researcher" / "2026-05-17_sec_s5_mr_ensemble_retest.md"

TOP4 = {"vsa_climax_test", "brooks_failed_breakout",
        "anchored_vwap_reversal", "engulfing_continuation"}
SYMS = {"BTC/USDT", "ETH/USDT", "SOL/USDT", "BNB/USDT", "ADA/USDT",
        "AVAX/USDT", "LINK/USDT", "DOT/USDT", "DOGE/USDT", "XRP/USDT"}

# Walk-forward params
TRAIN_DAYS = 2 * 365
OOS_DAYS = 90
STEP_DAYS = 30


def to_utc(ts):
    return ts.replace(tzinfo=timezone.utc) if ts.tzinfo is None else ts.astimezone(timezone.utc)


def build_windows(trades, train_days=TRAIN_DAYS, oos_days=OOS_DAYS, step_days=STEP_DAYS):
    trades.sort(key=lambda x: x["entry_ts"])
    start = trades[0]["entry_ts"]
    end = trades[-1]["exit_ts"]
    out = []
    cur = start
    while cur + pd.Timedelta(days=train_days + oos_days) <= end:
        out.append((cur, cur + pd.Timedelta(days=train_days)))
        cur += pd.Timedelta(days=step_days)
    return out


def walk_forward(pool, cfg, years=TRAIN_DAYS/365.0):
    pool = sorted(pool, key=lambda x: x["entry_ts"])
    windows = build_windows(pool)
    anns, dds, neg, n_trades_total = [], [], 0, 0
    for ws, we in windows:
        w = [t for t in pool if ws <= t["entry_ts"] < we]
        if not w:
            continue
        r = production_replay(w, cfg)
        if r is None:
            continue
        ann = r.annualized(years) * 100
        dd = r.max_drawdown * 100
        anns.append(ann); dds.append(dd); n_trades_total += r.trades
        if ann < 0: neg += 1
    if not anns:
        return None
    ma = stat_mean(anns); md = stat_mean(dds)
    return {
        "n_win": len(anns),
        "neg": neg,
        "ann_mean": ma,
        "ann_min": min(anns),
        "ann_max": max(anns),
        "dd_mean": md,
        "r_adj": ma / abs(md) if md != 0 else 0,
        "n_trades_total": n_trades_total,
    }


def per_month(pool, cfg):
    pool = sorted(pool, key=lambda x: to_utc(x["entry_ts"]))
    start = to_utc(pool[0]["entry_ts"])
    end = to_utc(pool[-1]["entry_ts"])

    months = []
    cy, cm = start.year, start.month
    while True:
        ms = datetime(cy, cm, 1, tzinfo=timezone.utc)
        if cm == 12:
            me = datetime(cy + 1, 1, 1, tzinfo=timezone.utc)
        else:
            me = datetime(cy, cm + 1, 1, tzinfo=timezone.utc)
        if ms > end:
            break
        months.append((cy, cm, ms, me))
        cm += 1
        if cm > 12:
            cm = 1; cy += 1

    rets = []
    zero_months = 0
    neg_months = 0
    n_months_with_trades = 0
    for yr, mo, ms, me in months:
        m_tr = [t for t in pool if ms <= to_utc(t["entry_ts"]) < me]
        if len(m_tr) < 1:
            zero_months += 1
            rets.append(0.0)
            continue
        if len(m_tr) < 10:
            # too few - treat as zero return for stability
            rets.append(0.0)
            continue
        r = production_replay(m_tr, cfg)
        if r is None:
            rets.append(0.0)
            continue
        ret_pct = r.total_return * 100
        rets.append(ret_pct)
        n_months_with_trades += 1
        if ret_pct < 0:
            neg_months += 1
    if not rets:
        return None
    mu = stat_mean(rets)
    sd = stdev(rets) if len(rets) > 1 else 0.0
    return {
        "n_months": len(months),
        "mean_pct": mu,
        "stdev_pct": sd,
        "cv_pct": (sd / abs(mu) * 100) if mu != 0 else 1e9,
        "zero_months": zero_months,
        "neg_months": neg_months,
        "min_pct": min(rets),
        "max_pct": max(rets),
        "n_months_with_trades": n_months_with_trades,
    }


def scenario(name, pool, cfg, w):
    w(f"### {name}")
    w("")
    if not pool:
        w("**SKIP** (empty pool)")
        w("")
        return None
    Rs = [t["R"] for t in pool]
    w(f"- Pool size: {len(pool):,} trades, mean R {sum(Rs)/len(Rs):+.3f}, sumR {sum(Rs):+.1f}")

    print(f"  [walk-forward] {name}...")
    wf = walk_forward(pool, cfg)
    if wf is None:
        w("- Walk-forward: NO RESULT")
        return None
    w(f"- Walk-forward (34-window): annual mean **{wf['ann_mean']:+.1f}%** "
      f"(min {wf['ann_min']:+.1f}%, max {wf['ann_max']:+.1f}%)")
    w(f"- DD mean: **{wf['dd_mean']:+.1f}%**, r-adj: **{wf['r_adj']:.2f}**")
    w(f"- Positive windows: {wf['n_win'] - wf['neg']}/{wf['n_win']}, total trades: {wf['n_trades_total']:,}")

    print(f"  [per-month] {name}...")
    pm = per_month(pool, cfg)
    if pm is None:
        w("- Per-month: NO RESULT")
        return wf
    w(f"- Per-month ({pm['n_months']} months):")
    w(f"  - Mean: **{pm['mean_pct']:+.2f}%** | stdev: {pm['stdev_pct']:.2f}% | CV: **{pm['cv_pct']:.0f}%**")
    w(f"  - Zero-trade months: **{pm['zero_months']}/{pm['n_months']}**")
    w(f"  - Negative months: **{pm['neg_months']}/{pm['n_months']}**")
    w(f"  - Min/Max: {pm['min_pct']:+.2f}% / {pm['max_pct']:+.2f}%")
    w("")
    return {"wf": wf, "pm": pm, "name": name}


def main():
    REPORT_OUT.parent.mkdir(parents=True, exist_ok=True)
    out_lines: list[str] = []

    def w(line: str = ""):
        print(line)
        out_lines.append(line)

    w("# SEC-S5 MR Pool — Ensemble Retest (15m R4 + MR)")
    w("")
    w(f"**Generated:** {pd.Timestamp.now('UTC').isoformat()}")
    w(f"**Walk-forward:** 2y train + 3mo OOS + 1mo step")
    w("")
    w("## User Mandate (baseline targets)")
    w("- Sıfır ay 20 -> <=8")
    w("- Negatif ay 9 -> <=6")
    w("- CV %223 -> <=%100")
    w("- Mean +%17.33 -> >=%20 (preserve)")
    w("- Annual +%735 -> >=+%400 (acceptable decline)")
    w("")

    # Load R4 pool
    print(f"[load] {POOL_R4.name}")
    with POOL_R4.open("rb") as f:
        r4_raw = pickle.load(f)
    pool_r4 = [t for t in r4_raw if t.get("strategy") in TOP4 and t.get("symbol") in SYMS]
    print(f"  R4 (TOP-4): {len(pool_r4):,} trades")

    # Load MR pool
    if not POOL_MR.exists():
        print(f"ERROR: MR pool cache missing {POOL_MR}")
        return
    print(f"[load] {POOL_MR.name}")
    with POOL_MR.open("rb") as f:
        mr_by_strat = pickle.load(f)
    for k, v in mr_by_strat.items():
        print(f"  MR {k}: {len(v):,} trades")

    # Load config
    cfg = ProductionConfig.from_yaml(str(YAML_R3)).with_overrides(max_concurrent=20)
    print(f"\n[cfg] {YAML_R3.name} (mc=20 override)")

    # ========================================================================
    # Scenarios
    # ========================================================================
    results = []

    # A. Baseline R4
    w("## Scenarios")
    w("")
    res = scenario("A. Baseline R4 (TOP-4 trend-cont only)", pool_r4, cfg, w)
    if res: results.append(res)

    # B. R4 + bollinger_fade
    bb_trades = mr_by_strat.get("bollinger_fade_mr", [])
    if bb_trades:
        pool_b = pool_r4 + bb_trades
        res = scenario("B. R4 + bollinger_fade_mr", pool_b, cfg, w)
        if res: results.append(res)

    # C. R4 + range_bo_failure
    bo_trades = mr_by_strat.get("range_bo_failure_mr", [])
    if bo_trades:
        pool_c = pool_r4 + bo_trades
        res = scenario("C. R4 + range_bo_failure_mr", pool_c, cfg, w)
        if res: results.append(res)

    # D. R4 + all MR pool
    all_mr = []
    for k, v in mr_by_strat.items():
        all_mr.extend(v)
    if all_mr:
        pool_d = pool_r4 + all_mr
        res = scenario("D. R4 + ALL MR (3 strategies)", pool_d, cfg, w)
        if res: results.append(res)

    # ========================================================================
    # Comparison vs mandate
    # ========================================================================
    w("## Verdict vs User Mandate")
    w("")
    w("| Scenario | Annual | DD | r-adj | Mean/mo | CV | Zero | Neg |")
    w("|---|---:|---:|---:|---:|---:|---:|---:|")
    for r in results:
        if not r:
            continue
        wf = r["wf"]
        pm = r["pm"]
        w(f"| {r['name'][:50]} | {wf['ann_mean']:+.1f}% | {wf['dd_mean']:+.1f}% | "
          f"{wf['r_adj']:.2f} | {pm['mean_pct']:+.2f}% | {pm['cv_pct']:.0f}% | "
          f"{pm['zero_months']} | {pm['neg_months']} |")
    w("")

    # Best candidate
    if len(results) > 1:
        best = None
        best_score = -1e9
        for r in results[1:]:  # skip baseline
            pm = r["pm"]; wf = r["wf"]
            # Score: high mean, low CV, low zero+neg, high annual
            score = pm["mean_pct"] - 0.001 * pm["cv_pct"] - 2 * (pm["zero_months"] + pm["neg_months"]) + 0.01 * wf["ann_mean"]
            if score > best_score:
                best_score = score
                best = r
        if best:
            w(f"**Best MR candidate:** {best['name']}")
            baseline = results[0]
            d_mean = best["pm"]["mean_pct"] - baseline["pm"]["mean_pct"]
            d_cv = best["pm"]["cv_pct"] - baseline["pm"]["cv_pct"]
            d_zero = best["pm"]["zero_months"] - baseline["pm"]["zero_months"]
            d_neg = best["pm"]["neg_months"] - baseline["pm"]["neg_months"]
            d_ann = best["wf"]["ann_mean"] - baseline["wf"]["ann_mean"]
            w(f"  - Mean delta: {d_mean:+.2f}pp")
            w(f"  - CV delta: {d_cv:+.0f}pp")
            w(f"  - Zero months delta: {d_zero:+d}")
            w(f"  - Neg months delta: {d_neg:+d}")
            w(f"  - Annual delta: {d_ann:+.1f}pp")
            w("")

            # Verdict
            mandate_pass = (
                best["pm"]["mean_pct"] >= 20.0
                and best["pm"]["cv_pct"] <= 100.0
                and best["pm"]["zero_months"] <= 8
                and best["pm"]["neg_months"] <= 6
                and best["wf"]["ann_mean"] >= 400.0
            )
            w(f"**MANDATE COMPLIANCE:** {'PASS' if mandate_pass else 'FAIL'}")
            if not mandate_pass:
                w("Reasons:")
                if best["pm"]["mean_pct"] < 20.0:
                    w(f"- mean_pct {best['pm']['mean_pct']:.2f}% < 20% target")
                if best["pm"]["cv_pct"] > 100.0:
                    w(f"- CV {best['pm']['cv_pct']:.0f}% > 100% target")
                if best["pm"]["zero_months"] > 8:
                    w(f"- zero_months {best['pm']['zero_months']} > 8 target")
                if best["pm"]["neg_months"] > 6:
                    w(f"- neg_months {best['pm']['neg_months']} > 6 target")
                if best["wf"]["ann_mean"] < 400.0:
                    w(f"- annual {best['wf']['ann_mean']:.1f}% < 400% red line")

    REPORT_OUT.write_text("\n".join(out_lines), encoding="utf-8")
    print(f"\n[report] {REPORT_OUT}")


if __name__ == "__main__":
    main()
