pairs:
  EURUSD-GBPUSD: 0.78
  EURUSD-AUDUSD: 0.55
  EURUSD-NZDUSD: 0.45
  EURUSD-USDCAD: -0.65
  EURUSD-USDCHF: -0.85
  EURUSD-EURGBP: 0.45
  EURUSD-EURJPY: 0.55
  GBPUSD-AUDUSD: 0.62
  GBPUSD-NZDUSD: 0.50
  GBPUSD-EURGBP: -0.45
  GBPUSD-GBPJPY: 0.55
  AUDUSD-NZDUSD: 0.85
  USDJPY-EURJPY: 0.55
  USDJPY-GBPJPY: 0.60
  USDCAD-USDCHF: 0.55
